"use client";
import { useState, type CSSProperties } from "react";
import { reportPeriods, type ReportPeriodKey } from "./reportData";
type MetricKey="fact"|"prepaid"|"weighted"|"raw";
const money=(v:number)=>v?`${(v/1e6).toLocaleString("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2})} млн ₽`:"0 ₽";
const pct=(v:number,p:number)=>p?v/p*100:0;
const labels:Record<MetricKey,string>={fact:"Факт · сделка успешна",prepaid:"Предоплачено",weighted:"Взвешенный pipeline",raw:"Сырой pipeline"};
const history={prepaid:[["20.08",50,12861661],["27.08",41,11619838],["03.09",24,5181700]],weighted:[["20.08",124,15258045],["27.08",107,18691570],["03.09",100,21248072]],raw:[["20.08",124,30350650],["27.08",107,34922900],["03.09",100,39182905]]} as const;
function Card({kind,data,closed}:{kind:MetricKey;data:(typeof reportPeriods)[ReportPeriodKey];closed:boolean}){const metric=data.total[kind];if(closed&&kind!=="fact")return <article className="kpi pipeline-kpi muted-kpi"><span>{labels[kind]}</span><strong>—</strong><small>Для закрытого августа показываем только факт</small></article>;const plan=kind==="fact"?data.plan:undefined;const completion=plan?pct(metric.sum,plan.total):0;return <article className={`kpi pipeline-kpi${kind==="weighted"?" accent":""}`}><span>{labels[kind]}</span><strong>{money(metric.sum)}</strong><small>{metric.count} сделок{plan?` · ${completion.toLocaleString("ru-RU",{maximumFractionDigits:1})}% плана`:""}</small>{plan&&<div className="plan-track"><i style={{"--plan":`${Math.min(completion,100)}%`} as CSSProperties}/></div>}<div className="kpi-average-values">{(["B2C","B2B"] as const).map(d=><span key={d}>{d}<b>{money(data[d][kind].sum)} · {data[d][kind].count} шт.</b>{plan&&<small>план {money(plan[d])} · {pct(data[d][kind].sum,plan[d]).toLocaleString("ru-RU",{maximumFractionDigits:1})}%</small>}</span>)}</div>{kind==="fact"&&<small className="year-comparison">2025: {money(data.comparison.y2025)} · 2024: {money(data.comparison.y2024)}</small>}</article>}
function Chart({kind}:{kind:keyof typeof history}){const rows=history[kind],maxCount=Math.max(...rows.map(r=>r[1])),maxSum=Math.max(...rows.map(r=>r[2]));const points=rows.map((r,i)=>`${(i+.5)/rows.length*100},${92-r[2]/maxSum*76}`).join(" ");return <div className="combo-card"><div className="combo-title"><div><h3>{labels[kind]}</h3><p>Сохранённое состояние в дату отчёта</p></div><span>столбцы — сделки · линия — сумма</span></div><div className="combo-scroll"><div className="combo-chart" style={{"--columns":rows.length} as CSSProperties}><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points}/></svg>{rows.map(r=><div className="combo-week" key={r[0]}><div className="combo-value"><span className="combo-count">Сделок: <b>{r[1]}</b></span><strong className="combo-sum">{money(r[2])}</strong></div><div className="combo-bar"><i style={{height:`${r[1]/maxCount*100}%`}}/></div><small>Снимок {r[0]}.2026</small></div>)}</div></div></div>}
export default function PipelineDashboard(){const[key,setKey]=useState<ReportPeriodKey>("september");return <section className="pipeline-dashboard" id="pipeline" data-dashboard><div className="period-toolbar reveal"><div><p className="eyebrow">Pipeline · выгрузки 3 сентября 2026</p><h2>Факт, предоплаты и прогноз</h2>{Object.entries(reportPeriods).map(([k,d])=><span key={k} data-period-range={k} hidden={key!==k}>{d.range}</span>)}</div><label><span>Период</span><select data-period-select value={key} onChange={e=>setKey(e.target.value as ReportPeriodKey)}>{Object.entries(reportPeriods).map(([k,d])=><option value={k} key={k}>{d.label}</option>)}</select></label></div>{Object.entries(reportPeriods).map(([k,data])=><div key={k} data-period-panel={k} hidden={key!==k}><div className="kpi-grid reveal">{(["fact","prepaid","weighted","raw"] as MetricKey[]).map(kind=><Card key={kind} kind={kind} data={data} closed={k==="august"}/>)}</div>{!data.plan&&<p className="annual-plan-note">План на период не задан; пустые месяцы считаются нулевыми.</p>}</div>)}<div className="snapshot-heading reveal"><p className="eyebrow">Динамика сохранённых снимков</p><h2>Состояние в даты формирования отчёта</h2><p>Графики отражают фактическое состояние стадий в каждый момент обновления, а не текущую последнюю стадию сделки.</p></div><div className="pipeline-charts reveal"><Chart kind="prepaid"/><Chart kind="weighted"/><Chart kind="raw"/></div><aside className="note reveal"><strong>Методика</strong><p>Факт — стадия «Сделка успешна». Предоплата и pipeline рассчитаны по согласованным стадиям и заполненному прогнозу. Сравнение 2024/2025 взято из блока «Коммерция» ParkOps.</p></aside></section>}
